### ISSUE TITLE
WSP 115

### ISSUE THREAD

**Issue by Headhunter70** [iobroker-community-adapters/ioBroker.mydlink#80]
Hi there, I was able to add the WSP 115 plug to the instance and I can see states changing false/true when switching the plug manually or via the app, however I can not change states from the instance.  log is the following:

mydlink.0 | 2020-12-09 16:28:37.988 | error | at DlinkSmarthome.onReady (/opt/iobroker/node_modules/iobroker.mydlink/main.js:728:37)
-- | -- | -- | --
mydlink.0 | 2020-12-09 16:28:37.988 | error | at DlinkSmarthome.startDevice (/opt/iobroker/node_modules/iobroker.mydlink/main.js:608:13)
mydlink.0 | 2020-12-09 16:28:37.988 | error | at DlinkSmarthome.loginDevice (/opt/iobroker/node_modules/iobroker.mydlink/main.js:435:31)
mydlink.0 | 2020-12-09 16:28:37.988 | error | at WebSocketClient.state (/opt/iobroker/node_modules/dlink_websocketclient/index.js:454:26)
mydlink.0 | 2020-12-09 16:28:37.988 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
mydlink.0 | 2020-12-09 16:28:37.988 | error | at WebSocketClient._getSetting (/opt/iobroker/node_modules/dlink_websocketclient/index.js:282:27)
mydlink.0 | 2020-12-09 16:28:37.988 | error | (32325) DSP-W115 could not login. Please check credentials and if  device is online/connected. Error: 403 - Error: API Error 424: invalid  device token

**Comment by ravijayaraman** [comment]
Are you using this in your, web project by any chance?

**Comment by Garfonso** [comment]
This is a node.js program, an adapter for IoBroker middlewade.

I also created a library to control the plugs, which is a better starting point for projects outside of IoBroker. This is still node.js, but since the plugs use websockets to communicate, maybe it would be possible to use in a web project. 

Here you can find the library https://github.com/Garfonso/dlinkWebSocketClient
